version: '3.8'

services:
  # ==========================================
  # 1. SERVIÇO DE BANCO DE DADOS (POSTGRESQL)
  # ==========================================
  db:
    image: postgres:15-alpine
    container_name: gateos_postgres
    restart: always
    environment:
      POSTGRES_USER: gateos_user
      POSTGRES_PASSWORD: SenhaSuperForte123
      POSTGRES_DB: gateos_db
    ports:
      - "5432:5432"
    volumes:
      # Mantém os dados salvos no seu HD mesmo se o container reiniciar
      - ./pgdata:/var/lib/postgresql/data

  # ==========================================
  # 2. SERVIÇO DA API (NODE.JS)
  # ==========================================
  api:
    build: .
    container_name: gateos_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Conexão com o banco (Note que usa '@db:5432' em vez de localhost)
      DATABASE_URL: "postgresql://gateos_user:SenhaSuperForte123@db:5432/gateos_db?schema=public"
      
      # Configurações do Servidor
      NODE_ENV: "production"
      PORT: "3000"
      JWT_SECRET: "gateos_super_secret_key_prod_change_me"
      FRONTEND_URL: "https://7ccd-200-252-153-98.ngrok-free.app" # Lembre-se de trocar pelo seu domínio oficial quando configurar o DNS!
      
      # Configurações Master
      SUPER_ADMIN_EMAIL: "master@cortextech.com"
      SUPER_ADMIN_PASS: "SenhaCabulosa123!@#"
      
      # Integração Asaas
      ASAAS_API_KEY: "$aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjkyZDFiMWRlLWQwY2QtNDU3OC1iODRiLTI5NmQ4MjZkM2QyMTo6JGFhY2hfNDMxMmFjYTAtNjJjZS00Mjg0LWE4NjItYzc4MGE3NWNjY2Yy"
      ASAAS_WEBHOOK: "whsec_I6Tx3vcDJhXpfpqGv7Qyi-uiu5RGshxdI2mFQDvTBgI"
      
      # Integração MQTT (Portões)
      MQTT_HOST: "e7ed4f597a2e4552bff29de8b6dba0d8.s1.eu.hivemq.cloud"
      MQTT_PORT: "8883"
      MQTT_USER: "AdminGateOS"
      MQTT_PASS: "6A1EAa40180C5A4399E6B1E89DAB79728F5E1DE9F777739462AD2331E8B3BF383"

volumes:
  db_data: